; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = lesson06_LightSensor

; Shared configuration inherited by every [env:*] below
[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps =
    arduino-libraries/Servo
    arduino-libraries/Stepper
    chris--a/Keypad
    z3t0/IRremote
    miguelbalboa/MFRC522
    makuna/Rtc
    adafruit/DHT sensor library

[env:lesson01_LED]
build_src_filter = -<*> +<lessons/lesson01_LED.cpp>

[env:lesson02_RGB]
build_src_filter = -<*> +<lessons/lesson02_RGB.cpp>

[env:lesson03_Buzzer]
build_src_filter = -<*> +<lessons/lesson03_Buzzer.cpp>

[env:lesson04_Button]
build_src_filter = -<*> +<lessons/lesson04_Button.cpp>

[env:lesson05_Potentiometer]
build_src_filter = -<*> +<lessons/lesson05_Potentiometer.cpp>

[env:lesson06_LightSensor]
build_src_filter = -<*> +<lessons/lesson06_LightSensor.cpp>